/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchedProductsRouteImport } from './routes/matched-products'
import { Route as MatchingRouteImport } from './routes/matching'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TrialExpiredRouteImport } from './routes/trial-expired'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAgenciesRouteImport } from './routes/admin/agencies'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminBrandsRouteImport } from './routes/admin/brands'
import { Route as AdminCampaignsRouteImport } from './routes/admin/campaigns'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AdminInfluencersRouteImport } from './routes/admin/influencers'
import { Route as AdminOffersRouteImport } from './routes/admin/offers'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminWalletsRouteImport } from './routes/admin/wallets'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin/withdrawals'
import { Route as AgencyCampaignsRouteImport } from './routes/agency.campaigns'
import { Route as AgencyClientsRouteImport } from './routes/agency.clients'
import { Route as AgencyEditingRouteImport } from './routes/agency.editing'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as BrandsBrandIdRouteImport } from './routes/brands.$brandId'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as InfluencerOffersRouteImport } from './routes/influencer.offers'
import { Route as InfluencerPricingRouteImport } from './routes/influencer.pricing'
import { Route as InfluencersIndexRouteImport } from './routes/influencers.index'
import { Route as InfluencersSlugRouteImport } from './routes/influencers.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as OffersIndexRouteImport } from './routes/offers.index'
import { Route as OffersIdRouteImport } from './routes/offers.$id'
import { Route as OffersBrowseRouteImport } from './routes/offers.browse'
import { Route as OffersNewRouteImport } from './routes/offers.new'
import { Route as PaymentsResultRouteImport } from './routes/payments.result'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as StudioContentRouteImport } from './routes/studio.content'
import { Route as StudioPhotographyRouteImport } from './routes/studio.photography'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchedProductsRoute = MatchedProductsRouteImport.update({
  id: '/matched-products',
  path: '/matched-products',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingRoute = MatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TrialExpiredRoute = TrialExpiredRouteImport.update({
  id: '/trial-expired',
  path: '/trial-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgenciesRoute = AdminAgenciesRouteImport.update({
  id: '/admin/agencies',
  path: '/admin/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/admin/brands',
  path: '/admin/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/admin/campaigns',
  path: '/admin/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/admin/finance',
  path: '/admin/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInfluencersRoute = AdminInfluencersRouteImport.update({
  id: '/admin/influencers',
  path: '/admin/influencers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/admin/offers',
  path: '/admin/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/admin/wallets',
  path: '/admin/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/admin/withdrawals',
  path: '/admin/withdrawals',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyCampaignsRoute = AgencyCampaignsRouteImport.update({
  id: '/agency/campaigns',
  path: '/agency/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyClientsRoute = AgencyClientsRouteImport.update({
  id: '/agency/clients',
  path: '/agency/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyEditingRoute = AgencyEditingRouteImport.update({
  id: '/agency/editing',
  path: '/agency/editing',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdRoute = BrandsBrandIdRouteImport.update({
  id: '/brands/$brandId',
  path: '/brands/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerOffersRoute = InfluencerOffersRouteImport.update({
  id: '/influencer/offers',
  path: '/influencer/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerPricingRoute = InfluencerPricingRouteImport.update({
  id: '/influencer/pricing',
  path: '/influencer/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencersIndexRoute = InfluencersIndexRouteImport.update({
  id: '/influencers/',
  path: '/influencers/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencersSlugRoute = InfluencersSlugRouteImport.update({
  id: '/influencers/$slug',
  path: '/influencers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIndexRoute = OffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIdRoute = OffersIdRouteImport.update({
  id: '/offers/$id',
  path: '/offers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersBrowseRoute = OffersBrowseRouteImport.update({
  id: '/offers/browse',
  path: '/offers/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersNewRoute = OffersNewRouteImport.update({
  id: '/offers/new',
  path: '/offers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsResultRoute = PaymentsResultRouteImport.update({
  id: '/payments/result',
  path: '/payments/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioContentRoute = StudioContentRouteImport.update({
  id: '/studio/content',
  path: '/studio/content',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioPhotographyRoute = StudioPhotographyRouteImport.update({
  id: '/studio/photography',
  path: '/studio/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/matched-products': typeof MatchedProductsRoute
  '/matching': typeof MatchingRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/pending': typeof PendingRoute
  '/plans': typeof PlansRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/trial-expired': typeof TrialExpiredRoute
  '/wallet': typeof WalletRoute
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/influencers': typeof AdminInfluencersRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/agency/campaigns': typeof AgencyCampaignsRoute
  '/agency/clients': typeof AgencyClientsRoute
  '/agency/editing': typeof AgencyEditingRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/influencer/offers': typeof InfluencerOffersRoute
  '/influencer/pricing': typeof InfluencerPricingRoute
  '/influencers/$slug': typeof InfluencersSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/offers/$id': typeof OffersIdRoute
  '/offers/browse': typeof OffersBrowseRoute
  '/offers/new': typeof OffersNewRoute
  '/payments/result': typeof PaymentsResultRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/studio/content': typeof StudioContentRoute
  '/studio/photography': typeof StudioPhotographyRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/admin/': typeof AdminIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/influencers/': typeof InfluencersIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/matched-products': typeof MatchedProductsRoute
  '/matching': typeof MatchingRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/pending': typeof PendingRoute
  '/plans': typeof PlansRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/trial-expired': typeof TrialExpiredRoute
  '/wallet': typeof WalletRoute
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/influencers': typeof AdminInfluencersRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/agency/campaigns': typeof AgencyCampaignsRoute
  '/agency/clients': typeof AgencyClientsRoute
  '/agency/editing': typeof AgencyEditingRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/influencer/offers': typeof InfluencerOffersRoute
  '/influencer/pricing': typeof InfluencerPricingRoute
  '/influencers/$slug': typeof InfluencersSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/offers/$id': typeof OffersIdRoute
  '/offers/browse': typeof OffersBrowseRoute
  '/offers/new': typeof OffersNewRoute
  '/payments/result': typeof PaymentsResultRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/studio/content': typeof StudioContentRoute
  '/studio/photography': typeof StudioPhotographyRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/admin': typeof AdminIndexRoute
  '/brands': typeof BrandsIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/influencers': typeof InfluencersIndexRoute
  '/offers': typeof OffersIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/matched-products': typeof MatchedProductsRoute
  '/matching': typeof MatchingRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/pending': typeof PendingRoute
  '/plans': typeof PlansRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/trial-expired': typeof TrialExpiredRoute
  '/wallet': typeof WalletRoute
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/influencers': typeof AdminInfluencersRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/agency/campaigns': typeof AgencyCampaignsRoute
  '/agency/clients': typeof AgencyClientsRoute
  '/agency/editing': typeof AgencyEditingRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/influencer/offers': typeof InfluencerOffersRoute
  '/influencer/pricing': typeof InfluencerPricingRoute
  '/influencers/$slug': typeof InfluencersSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/offers/$id': typeof OffersIdRoute
  '/offers/browse': typeof OffersBrowseRoute
  '/offers/new': typeof OffersNewRoute
  '/payments/result': typeof PaymentsResultRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/studio/content': typeof StudioContentRoute
  '/studio/photography': typeof StudioPhotographyRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/admin/': typeof AdminIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/influencers/': typeof InfluencersIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/billing'
    | '/dashboard'
    | '/knowledge'
    | '/login'
    | '/matched-products'
    | '/matching'
    | '/messages'
    | '/notifications'
    | '/pending'
    | '/plans'
    | '/recommendations'
    | '/register'
    | '/settings'
    | '/team'
    | '/trial-expired'
    | '/wallet'
    | '/admin/agencies'
    | '/admin/audit'
    | '/admin/brands'
    | '/admin/campaigns'
    | '/admin/finance'
    | '/admin/influencers'
    | '/admin/offers'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/agency/campaigns'
    | '/agency/clients'
    | '/agency/editing'
    | '/brands/$brandId'
    | '/campaigns/$id'
    | '/influencer/offers'
    | '/influencer/pricing'
    | '/influencers/$slug'
    | '/invite/$token'
    | '/offers/$id'
    | '/offers/browse'
    | '/offers/new'
    | '/payments/result'
    | '/products/$slug'
    | '/studio/content'
    | '/studio/photography'
    | '/teams/$teamId'
    | '/admin/'
    | '/brands/'
    | '/campaigns/'
    | '/influencers/'
    | '/offers/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/billing'
    | '/dashboard'
    | '/knowledge'
    | '/login'
    | '/matched-products'
    | '/matching'
    | '/messages'
    | '/notifications'
    | '/pending'
    | '/plans'
    | '/recommendations'
    | '/register'
    | '/settings'
    | '/team'
    | '/trial-expired'
    | '/wallet'
    | '/admin/agencies'
    | '/admin/audit'
    | '/admin/brands'
    | '/admin/campaigns'
    | '/admin/finance'
    | '/admin/influencers'
    | '/admin/offers'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/agency/campaigns'
    | '/agency/clients'
    | '/agency/editing'
    | '/brands/$brandId'
    | '/campaigns/$id'
    | '/influencer/offers'
    | '/influencer/pricing'
    | '/influencers/$slug'
    | '/invite/$token'
    | '/offers/$id'
    | '/offers/browse'
    | '/offers/new'
    | '/payments/result'
    | '/products/$slug'
    | '/studio/content'
    | '/studio/photography'
    | '/teams/$teamId'
    | '/admin'
    | '/brands'
    | '/campaigns'
    | '/influencers'
    | '/offers'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/billing'
    | '/dashboard'
    | '/knowledge'
    | '/login'
    | '/matched-products'
    | '/matching'
    | '/messages'
    | '/notifications'
    | '/pending'
    | '/plans'
    | '/recommendations'
    | '/register'
    | '/settings'
    | '/team'
    | '/trial-expired'
    | '/wallet'
    | '/admin/agencies'
    | '/admin/audit'
    | '/admin/brands'
    | '/admin/campaigns'
    | '/admin/finance'
    | '/admin/influencers'
    | '/admin/offers'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/agency/campaigns'
    | '/agency/clients'
    | '/agency/editing'
    | '/brands/$brandId'
    | '/campaigns/$id'
    | '/influencer/offers'
    | '/influencer/pricing'
    | '/influencers/$slug'
    | '/invite/$token'
    | '/offers/$id'
    | '/offers/browse'
    | '/offers/new'
    | '/payments/result'
    | '/products/$slug'
    | '/studio/content'
    | '/studio/photography'
    | '/teams/$teamId'
    | '/admin/'
    | '/brands/'
    | '/campaigns/'
    | '/influencers/'
    | '/offers/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  MatchedProductsRoute: typeof MatchedProductsRoute
  MatchingRoute: typeof MatchingRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PendingRoute: typeof PendingRoute
  PlansRoute: typeof PlansRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  TrialExpiredRoute: typeof TrialExpiredRoute
  WalletRoute: typeof WalletRoute
  AdminAgenciesRoute: typeof AdminAgenciesRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminInfluencersRoute: typeof AdminInfluencersRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AgencyCampaignsRoute: typeof AgencyCampaignsRoute
  AgencyClientsRoute: typeof AgencyClientsRoute
  AgencyEditingRoute: typeof AgencyEditingRoute
  BrandsBrandIdRoute: typeof BrandsBrandIdRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
  InfluencerOffersRoute: typeof InfluencerOffersRoute
  InfluencerPricingRoute: typeof InfluencerPricingRoute
  InfluencersSlugRoute: typeof InfluencersSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OffersIdRoute: typeof OffersIdRoute
  OffersBrowseRoute: typeof OffersBrowseRoute
  OffersNewRoute: typeof OffersNewRoute
  PaymentsResultRoute: typeof PaymentsResultRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  StudioContentRoute: typeof StudioContentRoute
  StudioPhotographyRoute: typeof StudioPhotographyRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  InfluencersIndexRoute: typeof InfluencersIndexRoute
  OffersIndexRoute: typeof OffersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matched-products': {
      id: '/matched-products'
      path: '/matched-products'
      fullPath: '/matched-products'
      preLoaderRoute: typeof MatchedProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching': {
      id: '/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof MatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trial-expired': {
      id: '/trial-expired'
      path: '/trial-expired'
      fullPath: '/trial-expired'
      preLoaderRoute: typeof TrialExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agencies': {
      id: '/admin/agencies'
      path: '/admin/agencies'
      fullPath: '/admin/agencies'
      preLoaderRoute: typeof AdminAgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/admin/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/admin/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/influencers': {
      id: '/admin/influencers'
      path: '/admin/influencers'
      fullPath: '/admin/influencers'
      preLoaderRoute: typeof AdminInfluencersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/admin/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/admin/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/admin/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/campaigns': {
      id: '/agency/campaigns'
      path: '/agency/campaigns'
      fullPath: '/agency/campaigns'
      preLoaderRoute: typeof AgencyCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/clients': {
      id: '/agency/clients'
      path: '/agency/clients'
      fullPath: '/agency/clients'
      preLoaderRoute: typeof AgencyClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/editing': {
      id: '/agency/editing'
      path: '/agency/editing'
      fullPath: '/agency/editing'
      preLoaderRoute: typeof AgencyEditingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId': {
      id: '/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof BrandsBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer/offers': {
      id: '/influencer/offers'
      path: '/influencer/offers'
      fullPath: '/influencer/offers'
      preLoaderRoute: typeof InfluencerOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer/pricing': {
      id: '/influencer/pricing'
      path: '/influencer/pricing'
      fullPath: '/influencer/pricing'
      preLoaderRoute: typeof InfluencerPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencers/': {
      id: '/influencers/'
      path: '/influencers'
      fullPath: '/influencers/'
      preLoaderRoute: typeof InfluencersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencers/$slug': {
      id: '/influencers/$slug'
      path: '/influencers/$slug'
      fullPath: '/influencers/$slug'
      preLoaderRoute: typeof InfluencersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/': {
      id: '/offers/'
      path: '/offers'
      fullPath: '/offers/'
      preLoaderRoute: typeof OffersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$id': {
      id: '/offers/$id'
      path: '/offers/$id'
      fullPath: '/offers/$id'
      preLoaderRoute: typeof OffersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/browse': {
      id: '/offers/browse'
      path: '/offers/browse'
      fullPath: '/offers/browse'
      preLoaderRoute: typeof OffersBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/new': {
      id: '/offers/new'
      path: '/offers/new'
      fullPath: '/offers/new'
      preLoaderRoute: typeof OffersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/result': {
      id: '/payments/result'
      path: '/payments/result'
      fullPath: '/payments/result'
      preLoaderRoute: typeof PaymentsResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/content': {
      id: '/studio/content'
      path: '/studio/content'
      fullPath: '/studio/content'
      preLoaderRoute: typeof StudioContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/photography': {
      id: '/studio/photography'
      path: '/studio/photography'
      fullPath: '/studio/photography'
      preLoaderRoute: typeof StudioPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  MatchedProductsRoute: MatchedProductsRoute,
  MatchingRoute: MatchingRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PendingRoute: PendingRoute,
  PlansRoute: PlansRoute,
  RecommendationsRoute: RecommendationsRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  TrialExpiredRoute: TrialExpiredRoute,
  WalletRoute: WalletRoute,
  AdminAgenciesRoute: AdminAgenciesRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBrandsRoute: AdminBrandsRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminInfluencersRoute: AdminInfluencersRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AgencyCampaignsRoute: AgencyCampaignsRoute,
  AgencyClientsRoute: AgencyClientsRoute,
  AgencyEditingRoute: AgencyEditingRoute,
  BrandsBrandIdRoute: BrandsBrandIdRoute,
  CampaignsIdRoute: CampaignsIdRoute,
  InfluencerOffersRoute: InfluencerOffersRoute,
  InfluencerPricingRoute: InfluencerPricingRoute,
  InfluencersSlugRoute: InfluencersSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  OffersIdRoute: OffersIdRoute,
  OffersBrowseRoute: OffersBrowseRoute,
  OffersNewRoute: OffersNewRoute,
  PaymentsResultRoute: PaymentsResultRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  StudioContentRoute: StudioContentRoute,
  StudioPhotographyRoute: StudioPhotographyRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  BrandsIndexRoute: BrandsIndexRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  InfluencersIndexRoute: InfluencersIndexRoute,
  OffersIndexRoute: OffersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
