/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchedProductsRouteImport } from './routes/matched-products'
import { Route as MatchingRouteImport } from './routes/matching'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TeamRouteImport } from './routes/team'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as BrandsBrandIdRouteImport } from './routes/brands.$brandId'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CampaignsSlugRouteImport } from './routes/campaigns.$slug'
import { Route as InfluencersIndexRouteImport } from './routes/influencers.index'
import { Route as InfluencersSlugRouteImport } from './routes/influencers.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as StudioContentRouteImport } from './routes/studio.content'
import { Route as StudioPhotographyRouteImport } from './routes/studio.photography'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchedProductsRoute = MatchedProductsRouteImport.update({
  id: '/matched-products',
  path: '/matched-products',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingRoute = MatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdRoute = BrandsBrandIdRouteImport.update({
  id: '/brands/$brandId',
  path: '/brands/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsSlugRoute = CampaignsSlugRouteImport.update({
  id: '/campaigns/$slug',
  path: '/campaigns/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencersIndexRoute = InfluencersIndexRouteImport.update({
  id: '/influencers/',
  path: '/influencers/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencersSlugRoute = InfluencersSlugRouteImport.update({
  id: '/influencers/$slug',
  path: '/influencers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioContentRoute = StudioContentRouteImport.update({
  id: '/studio/content',
  path: '/studio/content',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioPhotographyRoute = StudioPhotographyRouteImport.update({
  id: '/studio/photography',
  path: '/studio/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/matched-products': typeof MatchedProductsRoute
  '/matching': typeof MatchingRoute
  '/pending': typeof PendingRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/campaigns/$slug': typeof CampaignsSlugRoute
  '/influencers/$slug': typeof InfluencersSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/studio/content': typeof StudioContentRoute
  '/studio/photography': typeof StudioPhotographyRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/brands/': typeof BrandsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/influencers/': typeof InfluencersIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/matched-products': typeof MatchedProductsRoute
  '/matching': typeof MatchingRoute
  '/pending': typeof PendingRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/campaigns/$slug': typeof CampaignsSlugRoute
  '/influencers/$slug': typeof InfluencersSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/studio/content': typeof StudioContentRoute
  '/studio/photography': typeof StudioPhotographyRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/brands': typeof BrandsIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/influencers': typeof InfluencersIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/matched-products': typeof MatchedProductsRoute
  '/matching': typeof MatchingRoute
  '/pending': typeof PendingRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/campaigns/$slug': typeof CampaignsSlugRoute
  '/influencers/$slug': typeof InfluencersSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/studio/content': typeof StudioContentRoute
  '/studio/photography': typeof StudioPhotographyRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/brands/': typeof BrandsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/influencers/': typeof InfluencersIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/billing'
    | '/dashboard'
    | '/knowledge'
    | '/login'
    | '/matched-products'
    | '/matching'
    | '/pending'
    | '/recommendations'
    | '/register'
    | '/settings'
    | '/team'
    | '/brands/$brandId'
    | '/campaigns/$slug'
    | '/influencers/$slug'
    | '/invite/$token'
    | '/products/$slug'
    | '/studio/content'
    | '/studio/photography'
    | '/teams/$teamId'
    | '/brands/'
    | '/campaigns/'
    | '/influencers/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/billing'
    | '/dashboard'
    | '/knowledge'
    | '/login'
    | '/matched-products'
    | '/matching'
    | '/pending'
    | '/recommendations'
    | '/register'
    | '/settings'
    | '/team'
    | '/brands/$brandId'
    | '/campaigns/$slug'
    | '/influencers/$slug'
    | '/invite/$token'
    | '/products/$slug'
    | '/studio/content'
    | '/studio/photography'
    | '/teams/$teamId'
    | '/brands'
    | '/campaigns'
    | '/influencers'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/billing'
    | '/dashboard'
    | '/knowledge'
    | '/login'
    | '/matched-products'
    | '/matching'
    | '/pending'
    | '/recommendations'
    | '/register'
    | '/settings'
    | '/team'
    | '/brands/$brandId'
    | '/campaigns/$slug'
    | '/influencers/$slug'
    | '/invite/$token'
    | '/products/$slug'
    | '/studio/content'
    | '/studio/photography'
    | '/teams/$teamId'
    | '/brands/'
    | '/campaigns/'
    | '/influencers/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  MatchedProductsRoute: typeof MatchedProductsRoute
  MatchingRoute: typeof MatchingRoute
  PendingRoute: typeof PendingRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  BrandsBrandIdRoute: typeof BrandsBrandIdRoute
  CampaignsSlugRoute: typeof CampaignsSlugRoute
  InfluencersSlugRoute: typeof InfluencersSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  StudioContentRoute: typeof StudioContentRoute
  StudioPhotographyRoute: typeof StudioPhotographyRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  InfluencersIndexRoute: typeof InfluencersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matched-products': {
      id: '/matched-products'
      path: '/matched-products'
      fullPath: '/matched-products'
      preLoaderRoute: typeof MatchedProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching': {
      id: '/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof MatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId': {
      id: '/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof BrandsBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$slug': {
      id: '/campaigns/$slug'
      path: '/campaigns/$slug'
      fullPath: '/campaigns/$slug'
      preLoaderRoute: typeof CampaignsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencers/': {
      id: '/influencers/'
      path: '/influencers'
      fullPath: '/influencers/'
      preLoaderRoute: typeof InfluencersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencers/$slug': {
      id: '/influencers/$slug'
      path: '/influencers/$slug'
      fullPath: '/influencers/$slug'
      preLoaderRoute: typeof InfluencersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/content': {
      id: '/studio/content'
      path: '/studio/content'
      fullPath: '/studio/content'
      preLoaderRoute: typeof StudioContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/photography': {
      id: '/studio/photography'
      path: '/studio/photography'
      fullPath: '/studio/photography'
      preLoaderRoute: typeof StudioPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  MatchedProductsRoute: MatchedProductsRoute,
  MatchingRoute: MatchingRoute,
  PendingRoute: PendingRoute,
  RecommendationsRoute: RecommendationsRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  BrandsBrandIdRoute: BrandsBrandIdRoute,
  CampaignsSlugRoute: CampaignsSlugRoute,
  InfluencersSlugRoute: InfluencersSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  StudioContentRoute: StudioContentRoute,
  StudioPhotographyRoute: StudioPhotographyRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  BrandsIndexRoute: BrandsIndexRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  InfluencersIndexRoute: InfluencersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
